# Configuration parameters
model: "../../models/yolov8s.pt"
data: "../../data/drones_other/data.yaml"
save_period: 20
device: 0
amp: true
plots: true
save: true
show: true

# Output specificifations for train results
train_project: "../../data/model_results/train_results"
train_name: "train_result"

# Output specificifations for train results
test_project: "../../data/model_results/test_results"
test_name: "test_result"

# Hyperparameters
epochs: 200
patience: 25
imgsz: 832
batch: -1
lr0: 0.01
lrf: 0.01
fraction: 1.0

# Augmentation parameters
hsv_h: 0
hsv_s: 0
hsv_v: 0
fliplr: 0.5
scale: 0.5
degrees: 0
mosaic: 1

# Path to model weights
weights_path: "../../data/model_results/train_results/train_result3/weights/best.pt"

# Path to the image for inference
folder_or_file: "folder"
folder_path: "../../data/examples"
file_path: "../../data/examples/drone28.mp4"

# Hyperparameters for fine-tuning validation/test performance
iou: 0.4
conf: 0.1
split: "val"

# Configuration variables for dataset loading script
subset_folder: 'C:\Users\SujayTalanki\Downloads\subset2\images'
annotations_source: 'C:\Users\SujayTalanki\Downloads\dataset2\Annotations'
folder_path_modify: 'C:\Users\SujayTalanki\Downloads\subset2\annotations'
extend: true
